# Generated by Django 5.0.6 on 2024-07-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('resumen', models.TextField(max_length=1255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
